service: trigger-dynamo

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DYNAMODB_TABLE: Heroes
  iamRoleStatements:
    - Effect: Allow
      Actions:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

resources:
  Resources:
    HeroesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributesDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: nome
            AttributeType: S

functions:
  hero-insert:
    handler: handler.heroesInsert
    events:
      - http:
          path: heroes
          method: post
          cors: true