apiVersion: apps/v1
kind: Deployment
metadata:
  name: oceanize-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oceanize
  template:
    metadata: 
      labels:
        app: oceanize
    spec:
      containers:
        - name: oceanize
          image: gumberss/elixir-test
          env:
            - name: PGHOST
              value: "oceanize-db-srv"
            - name: PGPORT 
              value: "5432"
            - name: PGUSER
              value: postgres
            - name: PGDATABASE
              value: oceanize

---
apiVersion: v1
kind: Service
metadata:
  name: oceanize-srv
spec:
  selector:
    app: oceanize
  ports:
    - name: oceanize-port
      protocol: TCP
      port: 4000
      targetPort: 4000